// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AAnchorLink: typeof import('ant-design-vue/es')['AnchorLink']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AComment: typeof import('ant-design-vue/es')['Comment']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ArticleAnchor: typeof import('./src/components/article-item/article-anchor.vue')['default']
    ArticleAuthor: typeof import('./src/components/article-item/article-author.vue')['default']
    ArticleComment: typeof import('./src/components/article-comment/article-comment.vue')['default']
    ArticleItem: typeof import('./src/components/article-item/article-item.vue')['default']
    ArticleTagIcon: typeof import('./src/components/article-item/article-tag-icon.vue')['default']
    ArticleTags: typeof import('./src/components/article-item/article-tags.vue')['default']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CommentCloseButton: typeof import('./src/components/article-comment/comment-close-button.vue')['default']
    CommentInput: typeof import('./src/components/article-comment/comment-input.vue')['default']
    CommentItem: typeof import('./src/components/article-comment/comment-item.vue')['default']
    CommentList: typeof import('./src/components/article-comment/comment-list.vue')['default']
    FoldNav: typeof import('./src/components/nav-bar/fold-nav.vue')['default']
    FooterBar: typeof import('./src/components/footer-bar/index.vue')['default']
    HeaderBar: typeof import('./src/components/headr-bar/header-bar.vue')['default']
    HomeIntroducation: typeof import('./src/components/home/home-introducation.vue')['default']
    NavigationBar: typeof import('./src/components/nav-bar/navigation-bar.vue')['default']
    SeparateDot: typeof import('./src/components/separator/separate-dot.vue')['default']
    SeparateLine: typeof import('./src/components/separator/separate-line.vue')['default']
    VisitorLogin: typeof import('./src/components/visitor/visitor-login.vue')['default']
    VisitorRegister: typeof import('./src/components/visitor/visitor-register.vue')['default']
  }
}

export { }
