version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - add_ssh_keys:
          fingerprints:
            - "cf:55:11:a7:06:06:7a:83:73:46:93:6c:f9:14:63:9d"
      - checkout
      - restore_cache:
          keys: 
            - dependencies_circle_node
      - run:
          name: Install Pnpm
          command: sudo curl -f https://get.pnpm.io/v6.16.js | sudo node - add --global pnpm
      - run:
          name: Install
          command: pnpm install
      - save_cache:
          key: dependencies_circle_node
          paths:
            - node_modules
      - run:
          name: Build
          command: pnpm run build
      - run:
          name: AuthSet
          command: chmod +x scripts/deploy.sh
      - run:
          name: Deploy
          command: ./scripts/deploy.sh
workflows:
  basic-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - main